name: env_name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - psycopg2-binary
  - kafka-python
  - aiohttp
  - asyncpg
  - python-dotenv
  - kafka-python  # Optional: if you still want CLI tools
  - pip
  - pip:
    - requests
    - uvloop  # Optional: faster asyncio event loop for Linux/macOS
    - aiokafka
